name: Node.js CI

on:
  push:
    branches: [master, main, develop, dev/*]
  pull_request:
    branches: [master, main, develop, dev/*]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:prod